version: '3.8'
services:

  katerini.proxy:
    image: nginx:latest
    container_name: katerini.proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  katerini.website:
    image: katerini.website:latest
    container_name: katerini.website
    restart: unless-stopped
    ports: 
      - "15000:8080"
    environment:
      - DOTNET_ENVIRONMENT=Docker # just to make it easy to differentiate in the logs when running locally vs in docker
      - ConnectionStrings__RabbitMq=amqp://rabbitmq:5672
      - ConnectionStrings__SqlDatabase=Server=mssql;Database=Katerini;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - SeqLoggingConfiguration__ServerUrl=http://seq:5341
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  katerini.service:
    image: katerini.service:latest
    container_name: katerini.service
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=Docker # just to make it easy to differentiate in the logs when running locally vs in docker
      - ConnectionStrings__RabbitMq=amqp://rabbitmq:5672
      - ConnectionStrings__SqlDatabase=Server=mssql;Database=Katerini;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - SeqLoggingConfiguration__ServerUrl=http://seq:5341
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  katerini.mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: katerini.mssql
    restart: unless-stopped
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_USERNAME=sa
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log

  katerini.rabbitmq:
    image: rabbitmq:3.12-management
    container_name: katerini.rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/

  katerini.seq:
    image: datalust/seq:latest
    container_name: katerini.seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "15673:80"
    volumes:
      - seq_data:/data

  redis:
    image: redis:latest
    container_name: katerini.redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
  katerini.redis-webui:
    image: rediscommander/redis-commander:latest
    container_name: katerini.redis-webui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "15674:8081"
    restart: unless-stopped

volumes:
  mssql_data:
  mssql_log:
  redis_data:
  seq_data:
  rabbitmq_data:
  rabbitmq_logs: